# Generated by Django 6.0.7 on 2026-09-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='signatures',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
